inveniosoftware/invenio-previewer

CHANGES.rst
RELEASE-NOTES.rst
invenio_previewer/version.py
setup.py

Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>

Invenio-Previewer v0.1.0

---

.editorconfig
AUTHORS.rst
CHANGES.rst
INSTALL.rst
MANIFEST.in
RELEASE-NOTES.rst
docs/api.rst
docs/installation.rst
examples/app.py
invenio_previewer/__init__.py
invenio_previewer/bundles.py
invenio_previewer/extensions/zip.py
invenio_previewer/templates/invenio_previewer/base.html
invenio_previewer/templates/invenio_previewer/bottom.html
invenio_previewer/templates/invenio_previewer/default.html
invenio_previewer/version.py
invenio_previewer/views.py
run-tests.sh
setup.py
tests/conftest.py
tests/test_invenio_previewer.py
tests/test_invenio_previewer_views.py

WIP global: release preparation

---

.editorconfig
AUTHORS.rst
CHANGES.rst
INSTALL.rst
MANIFEST.in
RELEASE-NOTES.rst
docs/api.rst
docs/installation.rst
examples/app.py
invenio_previewer/__init__.py
invenio_previewer/bundles.py
invenio_previewer/config.py
invenio_previewer/extensions/csv_dthreejs.py
invenio_previewer/extensions/zip.py
invenio_previewer/static/css/pdfjs/viewer.css
invenio_previewer/templates/invenio_previewer/_macros.html
invenio_previewer/templates/invenio_previewer/base.html
invenio_previewer/templates/invenio_previewer/bottom.html
invenio_previewer/templates/invenio_previewer/default.html
invenio_previewer/templates/invenio_previewer/pdfjs.html
invenio_previewer/version.py
invenio_previewer/views.py
run-tests.sh
setup.py
tests/conftest.py
tests/test_invenio_previewer.py
tests/test_invenio_previewer_views.py

* Adds module usage documentation. (closes #9)
* Internationalizes PDFJS extension template,
* Moves extension configurations to config.py.
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>

global: addition of documentation

---

invenio_previewer/__init__.py
invenio_previewer/config.py
invenio_previewer/ext.py
setup.py

Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>

tests: docstring fix

---

invenio_previewer/bundles.py

* Reduces the library dependencies in generated bundles. (closes #13)
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>

bundles: reduction of bundle dependencies

---

examples/app.py
invenio_previewer/config.py
invenio_previewer/extensions/ipynb.py
invenio_previewer/templates/invenio_previewer/ipynb.html
setup.py
tests/test_macros.py

* Adds a new previewer which renders IPython notebook files. (closes #6)
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>

extensions: addition of IPython notebook preview

---

invenio_previewer/config.py

Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>
--
addresses #16

config: removal of duplicate value

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_previewer/version.py

Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>

release: v1.0.0a2

---

invenio_previewer/version.py

Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>

version: post-release bump

---

MANIFEST.in
README.rst
RELEASE-NOTES.rst
docs/requirements.txt

Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>

docs: ReadTheDocs configuration

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_previewer/version.py

Signed-off-by: Alexander Ioannidis <a.ioannidis@cern.ch>

release: v1.0.0a9

---

setup.py

Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

installation: fix nbconvert dependency

---

invenio_previewer/config.py
invenio_previewer/utils.py
setup.py
tests/test_utils.py

* Improved encoding detection.
* Better testing.
* Fixes installation issues on travis.
Solves #59 and https://github.com/zenodo/zenodo/issues/935 .

api: encoding detection

---

examples/app.py
invenio_previewer/bundles.py

fix assets generation in examples app

---

setup.cfg
tests/test_utils.py

Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

global: fix isort issues

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_previewer/version.py

Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

release: v1.0.0a11

---

README.rst
setup.py

readme: adding features to readme file

---

setup.py

* Closes inveniosoftware/invenio#3940
Signed-off-by: Jan Okraska <jan.okraska@cern.ch>

global: isort v4.3.4 and pytest v3.7.0

---

README.rst
docs/conf.py
examples/app.py
invenio_previewer/__init__.py
invenio_previewer/config.py
invenio_previewer/extensions/ipynb.py
invenio_previewer/views.py

docs: review, typos and rendering fixes

---

examples/app.py
invenio_previewer/templates/invenio_previewer/base.html

ext: pdf previewer & example app fix

---

CHANGES.rst
examples/app.py
examples/requirements.txt
invenio_previewer/extensions/ipynb.py
invenio_previewer/extensions/mistune.py
invenio_previewer/templates/invenio_previewer/ipynb.html
invenio_previewer/templates/invenio_previewer/mistune.html
invenio_previewer/utils.py
invenio_previewer/version.py
setup.py
tests/conftest.py
tests/test_macros.py
tests/test_utils.py

* Moves HTML sanitization logic to Invenio-Formatter (closes #96).

 global: use central logic for HTML sanitization

---

CHANGES.rst
invenio_previewer/version.py

release: v1.0.1

---

invenio_previewer/assets/css/simple_image/simple_image.css
invenio_previewer/assets/scss/simple_image.scss
invenio_previewer/assets/scss/style.scss
invenio_previewer/bundles.py
invenio_previewer/extensions/simple_image.py
invenio_previewer/templates/invenio_previewer/simple_image.html
invenio_previewer/webpack.py
setup.py
tests/test_macros.py

preview: fix inline style for content security policy

---

.travis.yml
CHANGES.rst
invenio_previewer/version.py
requirements-devel.txt
setup.py

* drop support for Python 2.7
* update travis.yml
closes #111

global: centrally manage flask dependency

---

invenio_previewer/templates/semantic-ui/invenio_previewer/macros.html

templates: Fixes file download link

---

CHANGES.rst
invenio_previewer/templates/semantic-ui/invenio_previewer/macros.html
invenio_previewer/version.py

Fixes: Fix question mark icon and preview button

---

setup.py

* nbconvert 5.x doesn't play nice with the recently released jinja2 3.1

setup: bump versions

---

invenio_previewer/translations/de/LC_MESSAGES/messages.po

* update de translations
related inveniosoftware/invenio-app-rdm#1664

i18n: update de translations

---

invenio_previewer/templates/invenio_previewer/zip.html
invenio_previewer/templates/semantic-ui/invenio_previewer/zip.html

Refs  https://github.com/inveniosoftware/invenio-app-rdm/issues/1707

i18n: Fixes strings marked for translation.

---

AUTHORS.rst
babel.ini

Fix err `AttributeError: module 'jinja2.ext' has no attribute 'autoescape' ` when extract messages for translation
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the …

config: fix extract messages err

---

invenio_previewer/assets/semantic-ui/scss/invenio_previewer/txt.scss
invenio_previewer/config.py
invenio_previewer/extensions/txt.py
invenio_previewer/templates/semantic-ui/invenio_previewer/txt.html
invenio_previewer/webpack.py
tests/test_macros.py

* Fixes horizontal scrolling in preview iframe
* Adds option to truncate .txt preview after a specified number of bytes
Fixes invenio-app-rdm#1864
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution …

txt-preview: improvments

---

invenio_previewer/utils.py

This PR resolves an issue with the text file previewer, where the encoding is detected as ASCII even though the file (and default) has utf8 characters beyond the detection range. Resolves https://github.com/inveniosoftware/invenio-previewer/issues/176 and partially resolves https://github.com/inveniosoftware/invenio-app-rdm/issues/1864
**Reminder**
By using GitHub, you have already …

encoding: override ASCII to default encoding

---

CHANGES.rst
invenio_previewer/version.py

Please describe briefly your pull request.
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …

release: v1.5.0

---

invenio_previewer/extensions/mistune.py
invenio_previewer/utils.py

Closes Issue [#310](https://github.com/zenodo/ops/issues/310)
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have …

markdown: fixed ascii encoding typo

---

.github/workflows/pypi-publish.yml
.github/workflows/tests.yml
CHANGES.rst
invenio_previewer/__init__.py
setup.cfg

- setup: pin dependencies
- setup: change to reusable workflows
- release: v2.2.2

pin dependencies

---

invenio_previewer/webpack.py

Closes https://github.com/inveniosoftware/invenio-previewer/issues/227

feat(pdfjs): bump pdfjs-dist to v5.x
